# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Manoj-SYS-193/RWPodSpecs.git'

target 'IceCreamSoup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IceCreamSoup
  pod 'RWPickFlavor', '~> 0.1.0'
  pod 'MBProgressHUD', '~> 1.1.0', :modular_headers => true

  target 'IceCreamSoupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IceCreamSoupUITests' do
    # Pods for testing
  end

end
